name: Build Hadoop 3.3.6

on:
  workflow_dispatch:
  push:
    branches: [ trunk ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Install dependencies
      run: |
       ls
    
    - name: Install dependencies
      run: |
       pwd
